-- test:

-- local match_parameter = helper.match_parameter
-- local check_trigger_char = helper.check_trigger_char
-- local signature1 = {
--   activeParameter = 1,
--   activeSignature = 0,
--   signatures = {
--     {
--       label = "newPerson2(name string, say string)",
--       parameters = {
--         {
--           label = "name string"
--         },
--         {
--           label = "say string"
--         }
--       }
--     }
--   }
-- }

-- local sig = match_parameter(signature1)
-- -- vim.inspect(signature1)

-- -- vim.inspect(sig)
-- local testlines2 = {"function t2(k: number, m: number)", " t2 a function return add"}
-- local signature2 = {
--   signatures = {
--     {
--       activeParameter = 1,
--       documentation = {
--         kind = "markdown",
--         value = " t2 a function return add"
--       },
--       label = "function t2(k: number, m: number)",
--       parameters = {
--         {
--           label = {12, 21}
--         },
--         {
--           label = {23, 32}
--         }
--       }
--     }
--   }
-- }
-- sig = match_parameter(signature2)
-- vim.inspect(signature2)
-- vim.inspect(sig)
